apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: empower-api
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/health-probe-path: /health/ping
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: empower-api-svc
                port:
                  number: 80
