apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../kustomize/
namespace: empowerdev
namePrefix: empowerdev-
patches:
- target:
    kind: Ingress
    name: empower-api
  path: ingress-patch.json 