apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/empower-api
namespace: capaxglobal
namePrefix: capaxglobal-
patches:
- target:
    kind: Ingress
    name: empower-api
  path: ingress-patch.json 